[project]
name = "common"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Hec7orci7o" }]
requires-python = ">=3.12"
dependencies = [
    "python-dotenv",
    "rich",
    "typer==0.12.3",
    "click<8.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
