[project]
name = "api-monitor-toolkit"
version = "0.1.0"
description = "API monitoring CLI tool"
readme = "README.md"
authors =  [{ name = "Hec7orci7o" }]
requires-python = ">=3.13"
dependencies = [
    "common",
    "psutil",
    "pefile",
    "requests",
    "pywin32",
    "rich",
    "typer==0.12.3",
    "click<8.2"
]

[tool.uv.sources]
common = { workspace = true }

[project.scripts]
api-monitor-toolkit = "api_monitor_toolkit.__init__:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
