[project]
name = "malware-downloader"
version = "0.1.0"
description = "A command-line tool to fetch malware samples, metadata, and behavioral intelligence"
readme = "README.md"
authors = [{ name = "Hec7orci7o" }, { name = "León AV" }]
requires-python = ">=3.12"
dependencies = [
    "python-dotenv",
    "vt-py",
    "malwarebazaar",
    "ratelimit",
    "rich",
    "typer",
]
