[project]
name = "malware-downloader"
version = "0.1.0"
description = "A command-line tool to fetch malware samples, metadata, and behavioral intelligence"
readme = "README.md"
authors = [{ name = "Hec7orci7o" }, { name = "León AV" }]
requires-python = ">=3.12"
dependencies = [
    "common",
    "python-dotenv",
    "vt-py",
    "malwarebazaar",
    "ratelimit",
    "rich",
    "typer==0.12.3",
    "click<8.2",
]

[tool.uv.sources]
common = { workspace = true }

[project.scripts]
malware-downloader = "malware_downloader.__init__:app"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
